spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.45.174.173:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
   host: smtp.163.com
   username: 13713698270@163.com
   password: VHCOVKKKLMUTCDYG
   default-encoding: UTF-8

ipFilter:
  interval: 1
  count: 2000
